# 3. Cómo responden los psicólogos sociales a las preguntas que se plantean: la investigación en psicología social  {.unnumbered #tema3}

Para que un conocimiento sea científico, se requiere que se haya llegado a él a través del método científico. Los Psicólogos Sociales no se contentan con saber qué hacen las personas, sino que quieren saber también por qué lo hacen. Para ello, derivan hipótesis de las teorías.

## 3.1. Teorías científicas: formulación y puesta a prueba de hipótesis {.unnumbered #subtema3_1}

Las teorías científicas son un conjunto de constructos, de ideas abstractas o conceptos que están relacionados entre sí siguiendo una lógica. Además, deben ser contrastables y, para ello, deben definir sus constructos teóricos operativamente. Si no pueden definirse, la teoría va más allá del ámbito de la ciencia.

Un constructo puede tener una o varias dimensiones. Por ejemplo, el constructo **agresión** puede incluir tanto agresión física o verbal, directa o indirecta, colérica o fría… De esta forma, la teoría integra los constructos y explica por qué es esperable que algo suceda de una forma y no en otra.

Los constructos son abstractos e inobservables (no es visible la agresión directamente, sino por medio de conductas agresivas). Por lo que los psicólogos sociales tienen que formular definiciones operativas de los constructos.

A partir de las teorías, los investigadores formulan hipótesis, que son soluciones tentativas a un problema, que deben ser contrastables, es decir, son predicciones formalmente establecidas sobre lo que puede causar que algo ocurra.
