# 4. Una breve historia de la psicología social {.unnumbered #tema4}

La psicología social comenzó como ciencia cuando se empezó a evaluar sistemática y formalmente los pensamientos, sentimientos y comportamientos de los seres humanos.

**Primer experimento:** No se sabe con exactitud cuál fue, pero el primero registrado fue por Triplett (1897), donde observó que los ciclistas registraban mejores marcas compitiendo contra otros que contra el reloj. Teorizó que la presencia de otros despertaba un instinto competitivo (energía nerviosa).

Otro experimento pionero fue el de un ingeniero sobre la **holgazanería social** (el efecto Ringelmann), que implica que cuántas más personas haya realizando una tarea, el esfuerzo individual se reduce conforme se aumenta el grupo. Por ejemplo, una persona ejerce 100 de fuerza tirando de una cuerda, pero cuando se une otra entre las dos realizan 186 de fuerza y no 200, por lo tanto, están por debajo de su potencial individual. Si hay ocho personas ejercen 392 en lugar de 800.

Lewin es considerado el padre de la psicología social, ya que expuso muchas ideas clave de la disciplina, incluyendo la interacción entre las personas y la situación.
