### 2 Comprensión colectiva o compartida {.unnumbered #subtema2_2_2}

Se relaciona estrechamente con la pertenencia. Es la necesidad de entender lo que creen los otros miembros del grupo o de llegar a un acuerdo compartido en la forma de ver el mundo. Esto permite a las personas predecir lo que sucederá en el futuro y entender lo que sucede en el presente.


Al pertenecer, se confía más en la conceptualización del mundo social dentro del grupo que en la de aquellos individuos que no pertenecen a él. Formar parte del grupo depende de percibir el mundo de la misma manera que los demás; de lo contrario, no se podría pertenecer, y se fomenta que las formas de ver la realidad de los que no pertenecen sean consideradas sesgadas o prejuiciosas.


Las investigaciones empíricas promueven la existencia universal de un motivo de comprensión compartida, pero hay líneas de investigación para explicar sus diferencias:


* **Colectivistas:** Enfatizan el acuerdo armonioso y unánime.
* **Individualistas:** Toleran interpretaciones individuales, incluso si van en contra del consenso social.


La falta de comprensión colectiva se refleja en la falta de información y poder de los miembros que no están adecuadamente integrados en el grupo. En las primeras etapas de pertenencia, se busca información sobre las normas del grupo y el papel que desempeñan los individuos dentro de él. Si no se logra una comprensión compartida, pueden mostrar conductas desviadas que los ponen en riesgo de devaluación, un componente central de la exclusión social.

