## 2\.6 Importancia de las relaciones sociales para el bienestar de las persona {.unnumbered #subtema2_6}

La importancia de las relaciones sociales para el bienestar de las personas es un tema que se basaba en el sentido común y la experiencia personal, pero que ha comenzado a investigarse científicamente en las últimas décadas.


La reducción de las familias extensas en el mundo occidental y la decisión de muchas personas adultas de pasar parte de su vida adulta solas, sin que esto signifique un menoscabo de su bienestar, han motivado estas investigaciones.


#### Evidencias {.unnumbered}


* **Biológica:** Cuando hay un sentido de identidad social compartida dentro de un grupo, se amortigua el estrés neuroendocrino.

* Pertenecer a muchos **grupos** (familia, trabajo, universidad) nos hace más saludables y resilientes.

* Un estudio en atención primaria mostró que el **aislamiento** tiene efectos negativos para la salud.

* Pertenecer a múltiples grupos sociales se asocia con un mayor **bienestar** psicológico y una mayor longevidad que pertenecer a pocos grupos sociales.


La **Pertenencia Grupal Múltiple** (MGM, por sus siglas en inglés, Multiple Group Membership) protege a las personas antes de que sucedan cambios importantes en la vida personal. La revisión de la literatura identifica efectos sobre el bienestar en relación con el estrés, la depresión, las adicciones, la conducta alimentaria y problemas crónicos de salud mental o física.


Existen evidencias sólidas de que el contacto social y la pertenencia a grupos tienen una fuerte influencia sobre la salud y la longevidad, mientras que la falta de contacto y el aislamiento constituyen factores de riesgo para una muerte prematura.

