### 4 Perfeccionamiento de sí mismo {.unnumbered #subtema2_2_4}

El perfeccionamiento de sí mismo se refiere a la necesidad de sentirse bien consigo mismo, mantener una autoestima razonablemente alta y verse a uno mismo como bueno, competente y decente.


En situaciones donde hay que elegir entre distorsionar la realidad para sentirse bien o percibir el mundo con precisión, la mayoría de las personas elige la primera opción. Para mantener una imagen positiva de sí mismos, están dispuestas a hacer cosas sorprendentes o paradójicas, como preferir a personas y situaciones que les han causado sufrimiento en lugar de aquellas que les agradan, si eso contribuye a su perfeccionamiento personal (por ejemplo, tolerar novatadas para ser aceptados).


Los seres humanos emplean un **sociometro**, que es un mecanismo que indica su posición dentro del grupo y les ayuda a vigilar su autoestima.


El motivo de perfeccionamiento de sí mismo es a menudo difícil de satisfacer, incluso para aquellos que son aceptados. Cuando las personas enfrentan amenazas en áreas relevantes para su autoestima, tienden a socavar sus relaciones interpersonales, lo que puede provocar emociones negativas como ira, tristeza o vergüenza, y una tendencia a centrarse en sí mismos, desviando la atención de los objetivos grupales.

