### 5 Confianza {.unnumbered #subtema2_2_5}



La confianza satisface la necesidad social de percibir el mundo como un lugar benevolente. Formar vínculos estrechos implica tener fe y confianza dentro del grupo. Las personas que confían ven la realidad social de forma más benévola y, como resultado, son más empáticas.


Confiar conlleva la contrapartida de excluir a otros, ya que las personas comparan a los miembros del grupo que son fiables con aquellos en quienes supuestamente no se puede confiar.


* **Individualistas:** La confianza se da por descontado. Se considera que todos son confiables y benignos hasta que se demuestre lo contrario. Esto se puede inferir incluso a partir de rasgos faciales en exposiciones muy breves, de menos de 100 milisegundos.

* **Colectivistas:** El círculo de confianza suele ser más estrecho y limitado a familiares cercanos y vínculos personales y profesionales consolidados. Tener confianza en los demás permite una mayor satisfacción con la realidad social, menos resentimiento, más éxito social y menos soledad.


La falta de confianza puede dañar la capacidad de formar relaciones constructivas. Por ejemplo, las personas traicionadas pueden volverse ultrasensibles al comportamiento de los demás, siendo más propensas a mentir, engañar y robar. También es menos probable que den una segunda oportunidad o que respeten los derechos de los demás.


**Marco de BUCKET:** Pertenencia, comprensión, control, estima y confianza.


Investigaciones recientes han tratado de analizar si los motivos sociales son válidos en distintas culturas. Los resultados mostraron que en países asiáticos (colectivistas), el motivo de pertenencia fue el más alto. Por otro lado, las amenazas sociales percibidas, el cambio cultural o el avance tecnológico correlacionan positivamente con todos los motivos sociales clave, aunque el vínculo más fuerte es con el motivo de control.

