### 2\.3\.3 El efecto de discontinuidad individuo\-grupo {.unnumbered #subtema2_3_3}

El efecto de discontinuidad individuo\-grupo se refiere a la tendencia de que las relaciones entre grupos sean más competitivas que las relaciones entre individuos. En el dilema del prisionero, la explicación para seguir una estrategia competitiva en la relación intergrupal puede agruparse en varios conjuntos: codicia y miedo.


* **Codicia:** Se espera que el contrincante coopere, haciéndolo más vulnerable.

* **Miedo:** Se espera que el contrincante compita y, por lo tanto, se convierta en una amenaza.


Por lo tanto, la codicia y el miedo pueden ser mayores en las relaciones entre grupos que en las interpersonales.

Otra explicación es que el grupo promueve el **egoísmo**, brindando apoyo social a estas conductas, mientras que este apoyo no está disponible para los individuos que actúan de forma aislada. 

Además, el **anonimato** proporcionado por los grupos, que no existe en las relaciones interpersonales, también contribuye a este fenómeno.

Finalmente, hay una *desconfianza* basada en *esquemas.* Al interactuar con otros grupos, se activan esquemas basados en el aprendizaje previo que nos llevan a *interacciones competitivas*, actuando de acuerdo con tales expectativas.

