## 1\.3 La Psicología Social busca comprender las causas del comportamiento social{.unnumbered  #subtema1_3}

Podemos agrupar las causas y condicionantes del comportamiento social en las siguientes categorías:

* **a) Conductas de otras personas:** Las acciones y expresiones de los demás tienen un impacto en nuestro comportamiento social, reaccionamos ante la conducta de los demás y ante los sentimientos y emociones que nos expresan.
* **b) Características físicas:** (atractivo físico, edad, grupo étnico…) son rasgos que influyen sobre nuestro comportamiento, aunque intentemos evitar conscientemente que lo hagan. La influencia no se limita únicamente a lo que vemos, también afecta a la información recibida por otros sentidos como el olfato.
* **c) Los grupos a los que pertenecen:** El grupo al que pertenece la persona evaluada afecta su evaluación. Ejemplo: currículums ciegos.
* **d) Nuestros procesos cognitivos:** Buscamos sentido al comportamiento de las personas atribuyendo sus acciones a características personales o circunstancias externas (ej: tráfico).
* **e) Características ambientales:** Las características del ambiente influyen en nuestros pensamientos, emociones y comportamientos sociales. Ejemplo: asociación entre temperatura y actos violentos.

------------------------------------------------------------

Asociación entre temperatura y actos violentos

Se producen más agresiones cuando las temperaturas son moderadamente altas que cuando son muy altas o bajas.

**Predictor de tiroteos masivos:**
- Mayor diferencia entre la temperatura actual y la esperada.
- Fines de semana.
- Festividades importantes (como Navidad).
- Estaciones más calurosas.
- Temperaturas más altas de lo normal.

 **Efecto de la Climatología y el Entorno**
Aparte de la climatología, también influye lo que visualizamos en nuestro entorno, como el dinero. Existe una relación entre ver una imagen de dinero y ser capaz de saborear un chocolate durante más tiempo.

**Estudio:**
Los participantes que visualizaron una foto de dinero pasaron menos tiempo comiendo el chocolate y mostraron menos disfrute. El recordatorio de la riqueza redujo la capacidad de los participantes de saborear la experiencia placentera de comer chocolate.

------------------------------------------------------------


* **f) Factores biológicos:** Las experiencias sociales pueden influir en el comportamiento a través de procesos epigenéticos que activan o desactivan genes específicos.

En este sentido, las experiencias con el estrés, especialmente en los primeros años de vida y en la edad adulta pueden ser causantes de cambios neurobiológicos que acaben afectando al bienestar psicológico.