## 1.2 La Psicología Social se centra en el comportamiento de las personas {.unnumbered  #subtema1_2}

El comportamiento de las personas es lo que estudiamos, ya que es observable y puede ser medido (por ejemplo, cuántos segundos tarda una persona en hacer una atribución de árabe\-malo en comparación con árabe\-bueno).


El comportamiento no se reduce únicamente a la conducta motriz (caminar, saltar…) sino también a todo aquello que expresamos oralmente, por escrito o gestualmente.

**El comportamiento como comunicación**

El comportamiento sirve para comunicar las motivaciones y metas que tienen las personas, así como sus pensamientos, emociones, creencias y actitudes.

- **Observable y medible**: Conducta motriz + expresiones.
- **Motivaciones y metas**: Pensamientos, emociones, creencias, actitudes y procesos psicológicos subyacentes.
- **Factores culturales o étnicos**: Presencia de los demás.

Estos aspectos son directamente observables. En situaciones donde las personas no los comunican explícitamente, pueden inferirse a partir del comportamiento, es decir, deducidos.

Por otro lado, el comportamiento también hace referencia a procesos psicológicos subyacentes (cognitivos o emocionales) no observables, que constituyen la dimensión psicológica del comportamiento.

Además, el comportamiento, los sentimientos y pensamientos están influenciados por factores culturales, étnicos y la presencia de los demás:

- **Física y real**: Como los espectadores de un partido que alientan o abuchean.
- **Imaginada**: Un opositor ensayando su exposición frente a un tribunal imaginado.
- **Simbólica o implícita**: No te sientas en una silla porque hay una chaqueta, y aunque la persona no está presente, nos abstenemos de ocupar el sitio.

La relación entre la conducta social y los procesos psicológicos subyacentes es de gran interés para los psicólogos sociales.
